name: 🐞 Bug melden
description: Kurzes Formular zum Melden von Fehlern
title: "[Bug] "
labels: ["bug"]

body:
  - type: input
    id: title
    attributes:
      label: Kurze Fehlerbeschreibung *
      placeholder: z. B. NPC greift nicht an
    validations:
      required: true

    - type: input
    id: involved-npc
    attributes:
      label: Involvierter NPC
      placeholder: z. B. Thrall, Hogger, Lady Sylvanas Windläufer
    validations:
      required: false

  - type: textarea
    id: current-behaviour
    attributes:
      label: Aktuelles Verhalten *
      placeholder: Was passiert derzeit im Spiel?
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Erwartetes Verhalten *
      placeholder: Was sollte stattdessen passieren?
    validations:
      required: true
      
  - type: textarea
    id: WoWHead-Link
    attributes:
      label: WoWHead-Link *
      placeholder: www.wowhead.com?
    validations:
      required: true

  - type: input
    id: zone
    attributes:
      label: Zone *
      placeholder: z. B. Durotar, Eiskrone, Tiefenbahn
    validations:
      required: true

  - type: input
    id: involved-npc
    attributes:
      label: Involvierter NPC
      placeholder: z. B. Thrall, Hogger, Lady Sylvanas Windläufer
    validations:
      required: false

  - type: input
    id: affected-character
    attributes:
      label: Betroffener Charaktername
      placeholder: z. B. MeinCharakter, TestChar01
    validations:
      required: false

